<?php

namespace FormArmorBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * InscriptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InscriptionRepository extends EntityRepository
{
    public function getInscriptions($idSession) // Liste toutes les sessions avec pagination
    {
        $queryBuilder = $this->createQueryBuilder('i')
            ->andWhere('i.session_formation = :idSession')
            ->setParameter('idSession', $idSession)
            ->orderBy('i.id', 'ASC');

        $query = $queryBuilder->getQuery();
        return $query->getResult();
    }
}
